kind = "DojoModel"
class_hash = "0x70f029e388626a8b775f9c8d03fbfb0326476da5dd1e1ee6a4079afba288b03"
original_class_hash = "0x70f029e388626a8b775f9c8d03fbfb0326476da5dd1e1ee6a4079afba288b03"
abi = "manifests/dev/abis/base/models/contracts_models_player_player.json"
name = "contracts::models::player::player"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "address"
type = "starknet::ContractAddress"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "supply"
type = "u32"
key = false

[[members]]
name = "real_tank_count"
type = "u8"
key = false

[[members]]
name = "dummy_tank_count"
type = "u8"
key = false

[[members]]
name = "last_action"
type = "u64"
key = false

[[members]]
name = "rank"
type = "u8"
key = false

[[members]]
name = "player_score"
type = "u32"
key = false

[[members]]
name = "turns_remaining"
type = "u8"
key = false

[[members]]
name = "turn_start_time"
type = "u64"
key = false

[[members]]
name = "reveal"
type = "bool"
key = false

[[members]]
name = "placements"
type = "u32"
key = false
