kind = "DojoModel"
class_hash = "0x33983839e4f50ffff3e13fd4cc10b86fa21c749499d6878a22e3bea6a6df229"
original_class_hash = "0x33983839e4f50ffff3e13fd4cc10b86fa21c749499d6878a22e3bea6a6df229"
abi = "manifests/dev/abis/base/models/contracts_models_game_game.json"
name = "contracts::models::game::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "next_to_move"
type = "ContractAddress"
key = false

[[members]]
name = "minimum_moves"
type = "u8"
key = false

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "player_count"
type = "u8"
key = false

[[members]]
name = "unit_count"
type = "u32"
key = false

[[members]]
name = "nonce"
type = "u32"
key = false

[[members]]
name = "price"
type = "u256"
key = false

[[members]]
name = "clock"
type = "u64"
key = false

[[members]]
name = "penalty"
type = "u64"
key = false

[[members]]
name = "limit"
type = "u32"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "dtanks_host"
type = "ContractAddress"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "weather"
type = "WeatherCondition"
key = false

[[members]]
name = "pending_reveals"
type = "u32"
key = false
