kind = "DojoModel"
class_hash = "0x619fe008b1a177a72b4b5030f78aa4dabfafb34ae7f6efafb7ef7c0d2f48ebe"
original_class_hash = "0x619fe008b1a177a72b4b5030f78aa4dabfafb34ae7f6efafb7ef7c0d2f48ebe"
abi = "manifests/dev/abis/base/models/contracts_models_tank_dtank.json"
name = "contracts::models::tank::dtank"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "ammunition"
type = "u32"
key = false

[[members]]
name = "health"
type = "u32"
key = false

[[members]]
name = "position"
type = "GridPosition"
key = false

[[members]]
name = "is_active"
type = "bool"
key = false

[[members]]
name = "target_id"
type = "u32"
key = false

[[members]]
name = "commitment"
type = "felt252"
key = false

[[members]]
name = "pending_damage"
type = "u32"
key = false
