[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x6019ff874cb7cf5f8ac22d824f37dcece028bfc1e634fd0150e5bae5186e17e"
transaction_hash = "0x7071c79b293ef70e515b5c4e011448d7c349858df1607447b73fb8540fe0f3e"
block_number = 3
seed = "contracts"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/dtankstest/katana"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x6901571cfa73e17d5be1c3a86c12dfbe25210fa461e915354bae223bba37a15"
class_hash = "0x52d7e35f46155c091955c3dff7cf3fefa7a9281293e38f995b4761df1fdabeb"
original_class_hash = "0x52d7e35f46155c091955c3dff7cf3fefa7a9281293e38f995b4761df1fdabeb"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/contracts_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::actions::actions"

[[contracts]]
kind = "DojoContract"
address = "0x6799df4857c44d232fefd3baa777acfb715844d5ea7ff2e97ed2bde5ae25ccc"
class_hash = "0x5dfa5641183959e3cc45b498dcaeef540e74594070bb3eec2fe85b5e9169d37"
original_class_hash = "0x5dfa5641183959e3cc45b498dcaeef540e74594070bb3eec2fe85b5e9169d37"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/contracts_systems_arena_arena.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::arena::arena"

[[models]]
kind = "DojoModel"
class_hash = "0x33983839e4f50ffff3e13fd4cc10b86fa21c749499d6878a22e3bea6a6df229"
original_class_hash = "0x33983839e4f50ffff3e13fd4cc10b86fa21c749499d6878a22e3bea6a6df229"
abi = "manifests/dev/abis/deployments/models/contracts_models_game_game.json"
name = "contracts::models::game::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "next_to_move"
type = "ContractAddress"
key = false

[[models.members]]
name = "minimum_moves"
type = "u8"
key = false

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "player_count"
type = "u8"
key = false

[[models.members]]
name = "unit_count"
type = "u32"
key = false

[[models.members]]
name = "nonce"
type = "u32"
key = false

[[models.members]]
name = "price"
type = "u256"
key = false

[[models.members]]
name = "clock"
type = "u64"
key = false

[[models.members]]
name = "penalty"
type = "u64"
key = false

[[models.members]]
name = "limit"
type = "u32"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "dtanks_host"
type = "ContractAddress"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "weather"
type = "WeatherCondition"
key = false

[[models.members]]
name = "pending_reveals"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x70f029e388626a8b775f9c8d03fbfb0326476da5dd1e1ee6a4079afba288b03"
original_class_hash = "0x70f029e388626a8b775f9c8d03fbfb0326476da5dd1e1ee6a4079afba288b03"
abi = "manifests/dev/abis/deployments/models/contracts_models_player_player.json"
name = "contracts::models::player::player"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "address"
type = "starknet::ContractAddress"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "supply"
type = "u32"
key = false

[[models.members]]
name = "real_tank_count"
type = "u8"
key = false

[[models.members]]
name = "dummy_tank_count"
type = "u8"
key = false

[[models.members]]
name = "last_action"
type = "u64"
key = false

[[models.members]]
name = "rank"
type = "u8"
key = false

[[models.members]]
name = "player_score"
type = "u32"
key = false

[[models.members]]
name = "turns_remaining"
type = "u8"
key = false

[[models.members]]
name = "turn_start_time"
type = "u64"
key = false

[[models.members]]
name = "reveal"
type = "bool"
key = false

[[models.members]]
name = "placements"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x619fe008b1a177a72b4b5030f78aa4dabfafb34ae7f6efafb7ef7c0d2f48ebe"
original_class_hash = "0x619fe008b1a177a72b4b5030f78aa4dabfafb34ae7f6efafb7ef7c0d2f48ebe"
abi = "manifests/dev/abis/deployments/models/contracts_models_tank_dtank.json"
name = "contracts::models::tank::dtank"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "unit_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "u32"
key = true

[[models.members]]
name = "ammunition"
type = "u32"
key = false

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "position"
type = "GridPosition"
key = false

[[models.members]]
name = "is_active"
type = "bool"
key = false

[[models.members]]
name = "target_id"
type = "u32"
key = false

[[models.members]]
name = "commitment"
type = "felt252"
key = false

[[models.members]]
name = "pending_damage"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x336e54a5e3683853cb5c7e85525db01cdebd306ff8ad8723d72ed634803986f"
original_class_hash = "0x336e54a5e3683853cb5c7e85525db01cdebd306ff8ad8723d72ed634803986f"
abi = "manifests/dev/abis/deployments/models/contracts_models_tile_tile.json"
name = "contracts::models::tile::tile"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "row"
type = "u32"
key = true

[[models.members]]
name = "col"
type = "u32"
key = true

[[models.members]]
name = "plants"
type = "PlantsPatch"
key = false

[[models.members]]
name = "tree"
type = "Tree"
key = false

[[models.members]]
name = "size"
type = "u32"
key = false

[[models.members]]
name = "occupied"
type = "bool"
key = false
